# Generated by Django 4.2.1 on 2023-05-22 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-posted'], 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-posted'], 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-launched'], 'verbose_name_plural': 'Discussions'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-posted'], 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='article',
            name='article_liked',
            field=models.ManyToManyField(blank=True, related_name='liked_articles', to='main.profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.project'),
        ),
        migrations.AlterField(
            model_name='like',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.article'),
        ),
        migrations.AlterField(
            model_name='like',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_liked',
            field=models.ManyToManyField(blank=True, related_name='liked_projects', to='main.profile'),
        ),
    ]
