# Generated by Django 4.2.1 on 2023-05-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_alter_article_article_liked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d'),
        ),
    ]
