# Generated by Django 4.2.1 on 2023-05-31 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_comment_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='photo',
            new_name='photos',
        ),
    ]
