# Generated by Django 4.2.1 on 2023-06-01 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_photo_comment_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('code', models.TextField()),
                ('info', models.TextField(blank=True, null=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('question_liked', models.ManyToManyField(blank=True, related_name='liked_questions', to='main.profile')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'ordering': ['-posted'],
            },
        ),
    ]
