# Generated by Django 4.2.1 on 2023-06-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='meetengine',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
