# Generated by Django 4.2.1 on 2023-06-01 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_question_meetengine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='media/img/%Y/%m/%d/')),
                ('content', models.TextField()),
                ('code', models.TextField()),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('moderation', models.BooleanField(default=False)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
            options={
                'verbose_name_plural': 'Answers',
                'ordering': ['-posted'],
            },
        ),
    ]
