# Generated by Django 4.2.1 on 2023-06-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_comment_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='info',
        ),
    ]
