# Generated by Django 4.2.1 on 2023-06-05 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_bio_profile_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_liked',
        ),
        migrations.AddField(
            model_name='article',
            name='article_saved',
            field=models.ManyToManyField(blank=True, related_name='saved_articles', to='main.profile'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='discussion_saved',
            field=models.ManyToManyField(blank=True, related_name='saved_discussions', to='main.profile'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_saved',
            field=models.ManyToManyField(blank=True, related_name='saved_projects', to='main.profile'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_saved',
            field=models.ManyToManyField(blank=True, related_name='saved_questions', to='main.profile'),
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Save', 'Save'), ('Unsave', 'Unsave')], max_length=8)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('saved', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.article')),
                ('discussion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.discussion')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.project')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
    ]
