# Generated by Django 4.2.1 on 2023-06-05 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_question_question_liked_article_article_saved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='save',
            options={'ordering': ['-saved'], 'verbose_name_plural': 'Savings'},
        ),
    ]
