# Generated by Django 4.2.1 on 2023-06-18 10:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_save_article_remove_save_discussion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('assigned', models.DateTimeField(auto_now_add=True)),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organiser_meetings', to='main.profile')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_meetings', to='main.profile')),
            ],
            options={
                'verbose_name_plural': 'Meetings',
                'ordering': ['-assigned'],
            },
        ),
    ]
